### ISSUE TITLE
Bounty: disassembler

### ISSUE THREAD

**Issue by AidenBeresford** [AidenBeresford/FeGBA#3]
# Write disassembler function that returns an instruction from an opcode. 
Each instruction is one point. You can only do one instruction at a time. When you choose an instruction you should write a reply to this issue so nobody else writes it before or after you. 

### ARM
~~Branch and Branch Exchange~~ 
~~Block Data Transfer~~
~~Branch and Branch with Link~~
~~Software Interrupt~~
~~Undefined~~
~~Single Data Transfer~~
~~Single Data Swap~~
~~Multiply and Multiply Long~~
~~Halfword Data Transfer Register / Immediate~~
~~PSR Transfer~~
~~Data Processing~~

### THUMB  
~~Software Interrupt~~
~~Unconditional Branch~~
~~Conditional Branch~~
~~Multiple Load / Store~~
~~Long Branch with Link~~
~~Add Offset to Stack Pointer~~
~~Push / Pop Register~~
~~Load / Store Halfword~~
~~SP Relative Load / Store~~
~~Load Address~~
~~Load / Store with Immediate Offset~~
~~Load / Store with Register Offset~~
~~Load / Store Sign-Extended Byte / Halfword~~
~~PC Relative Load~~
~~Hi Register Operation / Branch Exchange~~
~~ALU Operations~~
~~Move / Compare / Add / Subtract Immediate~~
~~Add / Subtract~~
~~Move Shifted Register~~

**Comment by AidenBeresford** [comment]
#2 adds is_branch_and_branch_exchange. Refer to this is a kind of style guide.

**Comment by aybanda** [comment]
@AidenBeresford Hey! I'd like to work on the ARM "Single Data Transfer" instruction for this bounty. Just claiming this one to avoid overlap. Cool if I get started on it?

**Comment by aybanda** [comment]
check this out #4 
completes
S̶i̶n̶g̶l̶e̶ D̶a̶t̶a̶ T̶r̶a̶n̶s̶f̶e̶r̶

**Comment by AidenBeresford** [comment]
> @AidenBeresford Hey! I'd like to work on the ARM "Single Data Transfer" instruction for this bounty. Just claiming this one to avoid overlap.

Hey, sorry for the confusion, not sure if you found this with a scraper or something. This is an org project for TAMU students. The bounties are a point system within the group. Your code is fine but I'm not going to accept your PR because you're not a member of the development team. Have a good one.

**Comment by AidenBeresford** [comment]
Oh, I see. My issue comes up if you search bounty and go to issues. I'll change the naming so this doesn't happen again. Whoops!

**Comment by aybanda** [comment]
no probs @AidenBeresford

**Comment by AidenBeresford** [comment]
Branch and Branch with Link, Software Interrupt, and Undefined added by #5

**Comment by AidenBeresford** [comment]
Remaining ARM instruction disassemblies added by #6 .

**Comment by AidenBeresford** [comment]
THUMB instructions added by #7
